apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spring-app-ingress
spec:
  podSelector:
    matchLabels:
      app: spring-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
